-- CULT Group Knowledge System v0.9
-- Run this once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text default '',
  role text not null default 'viewer' check (role in ('viewer','editor','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.knowledge_cards (
  id text primary key,
  section text not null check (section in ('contacts','content','money','situations')),
  status text not null default 'safe' check (status in ('safe','caution','blocked')),
  type text not null default 'Материал',
  title text not null,
  subtitle text not null default '',
  summary text not null default '',
  use_when text not null default '',
  tags text[] not null default '{}',
  sources integer[] not null default '{}',
  updated_date date not null default current_date,
  pinned boolean not null default false,
  details jsonb not null default '[]'::jsonb,
  detail_kind text not null default 'bullets' check (detail_kind in ('bullets','checklist','steps')),
  publish_state text not null default 'published' check (publish_state in ('published','draft','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.knowledge_history (
  id bigint generated by default as identity primary key,
  card_id text not null,
  action text not null,
  snapshot jsonb,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null
);

create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), 'viewer');
$$;

grant execute on function public.current_role() to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id,email,display_name,role)
  values (new.id,new.email,coalesce(new.raw_user_meta_data->>'display_name',''),'viewer')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.touch_knowledge_card()
returns trigger
language plpgsql
security invoker
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_knowledge_card on public.knowledge_cards;
create trigger trg_touch_knowledge_card
before update on public.knowledge_cards
for each row execute procedure public.touch_knowledge_card();

create or replace function public.log_knowledge_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    insert into public.knowledge_history(card_id,action,snapshot,changed_by)
    values(old.id,'delete',to_jsonb(old),auth.uid());
    return old;
  elsif tg_op = 'INSERT' then
    insert into public.knowledge_history(card_id,action,snapshot,changed_by)
    values(new.id,'insert',to_jsonb(new),auth.uid());
    return new;
  else
    insert into public.knowledge_history(card_id,action,snapshot,changed_by)
    values(new.id,'update',to_jsonb(new),auth.uid());
    return new;
  end if;
end;
$$;

drop trigger if exists trg_knowledge_history on public.knowledge_cards;
create trigger trg_knowledge_history
after insert or update or delete on public.knowledge_cards
for each row execute procedure public.log_knowledge_history();

alter table public.profiles enable row level security;
alter table public.knowledge_cards enable row level security;
alter table public.knowledge_history enable row level security;

-- PROFILES
drop policy if exists "profile read own or admin" on public.profiles;
drop policy if exists "profile admin update" on public.profiles;
create policy "profile read own or admin"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.current_role() = 'admin');

create policy "profile admin update"
on public.profiles for update
to authenticated
using (public.current_role() = 'admin')
with check (public.current_role() = 'admin');

-- KNOWLEDGE
drop policy if exists "knowledge read" on public.knowledge_cards;
drop policy if exists "knowledge insert editor" on public.knowledge_cards;
drop policy if exists "knowledge update editor" on public.knowledge_cards;
drop policy if exists "knowledge delete editor" on public.knowledge_cards;
create policy "knowledge read"
on public.knowledge_cards for select
to authenticated
using (publish_state = 'published' or public.current_role() in ('editor','admin'));

create policy "knowledge insert editor"
on public.knowledge_cards for insert
to authenticated
with check (public.current_role() in ('editor','admin'));

create policy "knowledge update editor"
on public.knowledge_cards for update
to authenticated
using (public.current_role() in ('editor','admin'))
with check (public.current_role() in ('editor','admin'));

create policy "knowledge delete editor"
on public.knowledge_cards for delete
to authenticated
using (public.current_role() in ('editor','admin'));

-- HISTORY
drop policy if exists "history read editor" on public.knowledge_history;
create policy "history read editor"
on public.knowledge_history for select
to authenticated
using (public.current_role() in ('editor','admin'));

-- Realtime support
alter table public.knowledge_cards replica identity full;
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='knowledge_cards'
  ) then
    alter publication supabase_realtime add table public.knowledge_cards;
  end if;
end $$;

-- After creating your FIRST account, promote it to Admin manually:
-- update public.profiles set role='admin' where email='YOUR_EMAIL@example.com';
